//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public long LogId { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Thread { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
        public string Transaction { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool deleted { get; set; }
    }
}
