//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationConfig
    {
        public int NotificationConfigId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> StatusTemplateId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AdditionalHeader { get; set; }
        public string AdditionalFooter { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual StatusTemplate StatusTemplate { get; set; }
    }
}
