//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentClaim
    {
        public long PaymentClaimId { get; set; }
        public long PaymentClaimNumber { get; set; }
        public Nullable<int> ClaimerId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Observation { get; set; }
        public bool IsAutomatic { get; set; }
        public bool IsLocked { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
