//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymentGatewayEntities : DbContext
    {
        public PaymentGatewayEntities()
            : base("name=PaymentGatewayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TransactionTicket>()
               .Property(t => t.TicketNumber)
               .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);

            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<PaymentClaim> PaymentClaim { get; set; }
        public virtual DbSet<AppConfig> AppConfig { get; set; }
        public virtual DbSet<Configurations> Configurations { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleCode> ModuleCode { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesConfig> ServicesConfig { get; set; }
        public virtual DbSet<VersionLog> VersionLog { get; set; }
        public virtual DbSet<NotificationConfig> NotificationConfig { get; set; }
        public virtual DbSet<NotificationLog> NotificationLog { get; set; }
        public virtual DbSet<NotificationTemplate> NotificationTemplate { get; set; }
        public virtual DbSet<StatusTemplate> StatusTemplate { get; set; }
        public virtual DbSet<TicketLog> TicketLog { get; set; }
        public virtual DbSet<TransactionTicket> TransactionTicket { get; set; }
        public virtual DbSet<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
        public virtual DbSet<TransactionResultInfo> TransactionResultInfo { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatus { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Pswd> Pswd { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserService> UserService { get; set; }
        public virtual DbSet<CodeMapping> CodeMapping { get; set; }
        public virtual DbSet<GenericCode> GenericCode { get; set; }
        public virtual DbSet<StatusCode> StatusCode { get; set; }
        public virtual DbSet<StatusMessage> StatusMessage { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<ProductsValidators> ProductsValidators { get; set; }
    }
}
