//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesConfig
    {
        public int ServiceConfigId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public bool RptToRendition { get; set; }
        public bool RptToConciliation { get; set; }
        public bool RptToCentralizer { get; set; }
        public int RenditionType { get; set; }
        public bool IsCallbackPosted { get; set; }
        public string SenderMail { get; set; }
        public string SenderURL { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsCommerceItemValidated { get; set; }
        public bool IsPaymentSecured { get; set; }
        public string ReportsPath { get; set; }
        public System.DateTime ReportBeginConciliation { get; set; }
        public System.DateTime ReportBeginCentralizer { get; set; }
        public System.DateTime ReportBeginRendition { get; set; }
        public bool IncludeBinInExport { get; set; }
        public bool ExcludeFromSPSBatchCloseInPaywayBO { get; set; }
    
        public virtual Services Services { get; set; }
    }
}
