//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketLog()
        {
            this.NotificationLog = new HashSet<NotificationLog>();
        }
    
        public int TicketLogId { get; set; }
        public long TicketNumber { get; set; }
        public string TypeFormat { get; set; }
        public string HtmlTicket { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationLog> NotificationLog { get; set; }
    }
}
