//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAdditionalInfo
    {
        public int TransactionAdditionalInfoId { get; set; }
        public long TransactionIdPK { get; set; }
        public string VersionUsed { get; set; }
        public string CustomerMail { get; set; }
        public int ProductId { get; set; }
        public int ServiceId { get; set; }
        public int ValidatorId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ExternalApp { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int ChannelId { get; set; }
        public int LanguageId { get; set; }
        public int CurrencyId { get; set; }
        public string MerchantId { get; set; }
        public string UniqueCode { get; set; }
        public int Payments { get; set; }
        public string BarCode { get; set; }
        public string CallbackUrl { get; set; }
        public Nullable<bool> IsEPCValidated { get; set; }
        public string EPCValidateURL { get; set; }
        public decimal CurrentAmount { get; set; }
        public string ProdVersionUsed { get; set; }
        public bool IsCommerceItemValidated { get; set; }
        public bool IsSimulation { get; set; }
        public long TransactionNumber { get; set; }
        public bool WasTimeOutForced { get; set; }
        public bool WasSyncByJob { get; set; }
        public Nullable<System.DateTime> ReportDateConciliation { get; set; }
        public Nullable<System.DateTime> ReportDateCentralizer { get; set; }
        public Nullable<System.DateTime> ReportDateRendition { get; set; }
        public string AuthorizationCode { get; set; }
        public string CardMask { get; set; }
        public string CardHolder { get; set; }
        public string TicketNumber { get; set; }
        public string BatchNbr { get; set; }
        public Nullable<System.DateTime> SynchronizationDate { get; set; }
        public Nullable<System.DateTime> BatchSPSDate { get; set; }
        public int LastStatus { get; set; }
        public Nullable<System.DateTime> ConfirmedByAutoBackOffice { get; set; }
        public Nullable<System.DateTime> ConfirmedByManualSupportOn { get; set; }
        public string ConfirmedByManualSupportBy { get; set; }
        public string OriginalReason { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Products Products { get; set; }
        public virtual Services Services { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
