//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionResultInfo
    {
        public int TransactionResultInfoId { get; set; }
        public long TransactionIdPK { get; set; }
        public string ResponseCode { get; set; }
        public string StateMessage { get; set; }
        public string StateExtendedMessage { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> Payments { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public string AuthorizationCode { get; set; }
        public string CardMask { get; set; }
        public string CardNbrLfd { get; set; }
        public string CardHolder { get; set; }
        public string CustomerDocType { get; set; }
        public string CustomerDocNumber { get; set; }
        public string TicketNumber { get; set; }
        public string CustomerEmail { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string BatchNbr { get; set; }
        public Nullable<System.DateTime> SynchronizationDate { get; set; }
        public Nullable<System.DateTime> BatchSPSDate { get; set; }
        public Nullable<System.DateTime> MailSynchronizationDate { get; set; }
    
        public virtual Transactions Transactions { get; set; }
    }
}
