//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transactions()
        {
            this.PaymentClaim = new HashSet<PaymentClaim>();
            this.TransactionAdditionalInfo = new HashSet<TransactionAdditionalInfo>();
            this.TransactionResultInfo = new HashSet<TransactionResultInfo>();
            this.TransactionStatus = new HashSet<TransactionStatus>();
        }
    
        public long Id { get; set; }
        public string InternalNbr { get; set; }
        public string Channel { get; set; }
        public string Client { get; set; }
        public string SalePoint { get; set; }
        public string Service { get; set; }
        public string Product { get; set; }
        public decimal Amount { get; set; }
        public string Validator { get; set; }
        public string WebSvcMethod { get; set; }
        public string TransactionId { get; set; }
        public string JSonObject { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int SettingId { get; set; }
        public string MerchantId { get; set; }
        public string ElectronicPaymentCode { get; set; }
        public string CurrencyCode { get; set; }
        public string TrxCurrencyCode { get; set; }
        public decimal TrxAmount { get; set; }
        public decimal ConvertionRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentClaim> PaymentClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionResultInfo> TransactionResultInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionStatus> TransactionStatus { get; set; }
    }
}
