//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TransactionTicket
    {
        public long TransactionTicketId { get; set; }
        public long TransactionIdPK { get; set; }
        public int StatusTemplateId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public long TicketNumber { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public bool SentBySync { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
