//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int UserServiceId { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual User User { get; set; }
    }
}
