//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionLog
    {
        public int VersionLogId { get; set; }
        public string Type { get; set; }
        public int Major { get; set; }
        public int Minor { get; set; }
        public int Maintenance { get; set; }
        public int Build { get; set; }
        public string Support { get; set; }
        public string Revision { get; set; }
        public int Deploy { get; set; }
        public string RequestBy { get; set; }
        public System.DateTime DeployDate { get; set; }
    }
}
