//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulmentRequest
    {
        public AnnulmentRequest()
        {
            this.AnnulmentJobLog = new HashSet<AnnulmentJobLog>();
            this.AnnulmentValidatorComm = new HashSet<AnnulmentValidatorComm>();
        }
    
        public int AnnulmentRequestId { get; set; }
        public Nullable<long> PaymentClaimId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ResponseModuleCode { get; set; }
        public string Result { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<AnnulmentJobLog> AnnulmentJobLog { get; set; }
        public virtual PaymentClaim PaymentClaim { get; set; }
        public virtual ICollection<AnnulmentValidatorComm> AnnulmentValidatorComm { get; set; }
    }
}
