//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulmentJobLog
    {
        public int AnnulmentJobLogId { get; set; }
        public int JobRunLogId { get; set; }
        public long PaymentClaimId { get; set; }
        public Nullable<int> AnnulmentRequestId { get; set; }
    
        public virtual AnnulmentRequest AnnulmentRequest { get; set; }
        public virtual JobRunLog JobRunLog { get; set; }
        public virtual PaymentClaim PaymentClaim { get; set; }
    }
}
