//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulmentValidatorComm
    {
        public int AnnulmentValidatorCommId { get; set; }
        public Nullable<int> AnnulmentRequestId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestMessage { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string ResponseMessage { get; set; }
    
        public virtual AnnulmentRequest AnnulmentRequest { get; set; }
    }
}
