//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulmentResultInfo
    {
        public int AnnulmentResultInfoId { get; set; }
        public long TransactionId { get; set; }
        public Nullable<long> PaymentClaimId { get; set; }
        public int ValidatorId { get; set; }
        public string OperationNumber { get; set; }
        public string AuthorizationCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime OriginalDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual PaymentClaim PaymentClaim { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
