//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarpendiStats
    {
        public long CarpendiStatsId { get; set; }
        public int Type { get; set; }
        public string Method { get; set; }
        public string Text { get; set; }
        public string DataRelated { get; set; }
        public long CarpendiProccessId { get; set; }
        public Nullable<long> TransactionIdPKRelated { get; set; }
        public string ErrorMessage { get; set; }
        public string ExceptionMessage { get; set; }
        public string InnerExceptionMessage { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
