//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims
    {
        public Claims()
        {
            this.ClaimOperations = new HashSet<ClaimOperations>();
        }
    
        public long Id { get; set; }
        public int ClaimTypeId { get; set; }
        public int ClaimStatusId { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentNbr { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string ClaimText { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public string ClaimExternalApp { get; set; }
        public Nullable<int> ClaimExternalOrderId { get; set; }
        public Nullable<bool> UpdCRMCase { get; set; }
        public Nullable<bool> UpdCRMInvoice { get; set; }
        public string CrmCaseId { get; set; }
    
        public virtual ICollection<ClaimOperations> ClaimOperations { get; set; }
        public virtual ClaimStatus ClaimStatus { get; set; }
        public virtual ClaimTypes ClaimTypes { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}
