//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimOperations
    {
        public ClaimOperations()
        {
            this.Refunds = new HashSet<Refunds>();
        }
    
        public long Id { get; set; }
        public long ClaimId { get; set; }
        public int ServiceId { get; set; }
        public int ProductId { get; set; }
        public long OriginalTrxId { get; set; }
        public long AmountCharged { get; set; }
        public byte[] CardInfo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Claims Claims { get; set; }
        public virtual ICollection<Refunds> Refunds { get; set; }
    }
}
