//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Services = new HashSet<Services>();
            this.TransactionAdditionalInfo = new HashSet<TransactionAdditionalInfo>();
        }
    
        public int ClientId { get; set; }
        public string TributaryCode { get; set; }
        public string ShortName { get; set; }
        public string LegalName { get; set; }
        public string SupportMail { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Services> Services { get; set; }
        public virtual ICollection<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
    }
}
