//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommerceItems
    {
        public CommerceItems()
        {
            this.CommerceItemClaim = new HashSet<CommerceItemClaim>();
            this.ReportJobLog = new HashSet<ReportJobLog>();
        }
    
        public long CommerceItemsId { get; set; }
        public long TransactionIdPK { get; set; }
        public string Code { get; set; }
        public string OriginalCode { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int State { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> ReportDateConciliation { get; set; }
        public Nullable<System.DateTime> ReportDateCentralizer { get; set; }
        public Nullable<System.DateTime> ReportDateRendition { get; set; }
    
        public virtual ICollection<CommerceItemClaim> CommerceItemClaim { get; set; }
        public virtual Transactions Transactions { get; set; }
        public virtual ICollection<ReportJobLog> ReportJobLog { get; set; }
    }
}
