//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationDefaultValues
    {
        public int Id { get; set; }
        public int ConfigurationId { get; set; }
        public int WebSvcMethodId { get; set; }
        public int WebSvcMethodParamId { get; set; }
        public string DefaultValue { get; set; }
        public string CastToCLRType { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual WebSvcMethodParams WebSvcMethodParams { get; set; }
        public virtual WebSvcMethods WebSvcMethods { get; set; }
    }
}
