//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationDetails
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int MainValidatorId { get; set; }
        public int MainValidatorMethodId { get; set; }
        public int MainValidatorRetries { get; set; }
        public Nullable<int> BckpValidatorId { get; set; }
        public Nullable<int> BckpValidatorMethodId { get; set; }
        public int BckpValidatorRetries { get; set; }
        public bool AutoFallback { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int ConfigurationId { get; set; }
    
        public virtual WebSvcMethods WebSvcMethods { get; set; }
        public virtual WebSvcMethods WebSvcMethods1 { get; set; }
    }
}
