//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetPrismaCodes
    {
        public int ProductId { get; set; }
        public string UniqueCode { get; set; }
        public int Normal { get; set; }
        public int Prisma { get; set; }
    }
}
