//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRunLog
    {
        public JobRunLog()
        {
            this.AnnulmentJobLog = new HashSet<AnnulmentJobLog>();
        }
    
        public int JobRunLogId { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
        public string Parameters { get; set; }
        public string SendNotificationTo { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AnnulmentJobLog> AnnulmentJobLog { get; set; }
    }
}
