//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.StatusMessage = new HashSet<StatusMessage>();
            this.TransactionAdditionalInfo = new HashSet<TransactionAdditionalInfo>();
        }
    
        public int Id { get; set; }
        public string ISO6391 { get; set; }
        public string ISO6392 { get; set; }
        public string ISO3166 { get; set; }
        public string NativeName { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<StatusMessage> StatusMessage { get; set; }
        public virtual ICollection<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
    }
}
