//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleCode
    {
        public ModuleCode()
        {
            this.CodeMapping = new HashSet<CodeMapping>();
        }
    
        public int ModuleCodeId { get; set; }
        public int ModuleId { get; set; }
        public string OriginalCode { get; set; }
        public string TechnicalInfo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<CodeMapping> CodeMapping { get; set; }
    }
}
