//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorSPSBatchProcessTransactions
    {
        public long MonitorSPSBatchProcessTransactionsId { get; set; }
        public long MonitorSPSBatchProcessFilesId { get; set; }
        public long TransactionIDPK { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> HasInconsistenceError { get; set; }
        public string InconsistenceError { get; set; }
        public Nullable<bool> InconsistenceDAYS { get; set; }
        public Nullable<bool> InconsistenceDUPS { get; set; }
        public Nullable<bool> InconsistenceDATE { get; set; }
        public Nullable<bool> InconsistenceUNIQ { get; set; }
        public Nullable<bool> InconsistenceCARD { get; set; }
        public Nullable<bool> InconsistenceCOST { get; set; }
    }
}
