//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorSPSBatchProcess
    {
        public long MonitorSPSBatchProcessId { get; set; }
        public System.DateTime BeginOn { get; set; }
        public Nullable<System.DateTime> EndOn { get; set; }
        public int FilesFound { get; set; }
        public int FilesRead { get; set; }
        public int TotalRecordsRead { get; set; }
        public int TotalRecordsNotRead { get; set; }
        public bool WithValidation { get; set; }
        public bool WithError { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsFTP { get; set; }
    }
}
