//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorPaywayBackOfficeTransactions
    {
        public long MonitorSPSBatchProcessTransactionsId { get; set; }
        public long ProcessId { get; set; }
        public long TransactionIDPK { get; set; }
        public int PGNewStatusId { get; set; }
        public int PGOldStatusId { get; set; }
        public long PGAmount { get; set; }
        public bool IsInPayway { get; set; }
        public bool PaywayAnullment { get; set; }
        public string PaywayStatus { get; set; }
        public Nullable<long> PaywayAmount { get; set; }
        public bool IsInconsistentAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
