//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorFilesReportRecords
    {
        public long MonitorFilesReportRecordsId { get; set; }
        public long MonitorFilesReportProcessId { get; set; }
        public long TransactionIdPK { get; set; }
        public bool IsTotalizer { get; set; }
        public bool IsIncomplete { get; set; }
        public bool Informed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
