//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorFilesReportProcess
    {
        public long MonitorFilesReportProcessId { get; set; }
        public System.DateTime BeginOn { get; set; }
        public Nullable<System.DateTime> EndDataOn { get; set; }
        public Nullable<System.DateTime> EndProcessOn { get; set; }
        public string RemoteFile { get; set; }
        public bool HasError { get; set; }
        public string Error { get; set; }
        public int TotalRecords { get; set; }
        public int TotalInformed { get; set; }
        public long InformedAmount { get; set; }
        public long IncompleteAmount { get; set; }
        public int Type { get; set; }
        public bool WereRollback { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
