//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorSyncroProcessRecords
    {
        public long MonitorSyncroProcessRecordsId { get; set; }
        public long MonitorSyncroProcessId { get; set; }
        public long TransactionIdPK { get; set; }
        public Nullable<System.DateTime> BeginProcess { get; set; }
        public Nullable<System.DateTime> EndProcess { get; set; }
        public Nullable<System.DateTime> ClosedByProcess { get; set; }
        public bool SPSBatchForced { get; set; }
        public bool HasError { get; set; }
        public string Error { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
