//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorSPSBatchProcessFiles
    {
        public long MonitorSPSBatchProcessFilesId { get; set; }
        public long MonitorSPSBatchProcessId { get; set; }
        public System.DateTime BeginOn { get; set; }
        public Nullable<System.DateTime> EndOn { get; set; }
        public string Filename { get; set; }
        public string ProductCode { get; set; }
        public string IDSITE { get; set; }
        public string FileDate { get; set; }
        public int TrailerRecords { get; set; }
        public int TrailerIdLote { get; set; }
        public int TrailerAutorizadas { get; set; }
        public int TrailerAnuladas { get; set; }
        public int TrailerDevueltas { get; set; }
        public long TrailerMontoAutorizadas { get; set; }
        public long TrailerMontoDevueltas { get; set; }
        public long TrailerMontoAnuladas { get; set; }
        public int TotalRecordsRead { get; set; }
        public int TotalRecordsNotRead { get; set; }
        public bool WithValidation { get; set; }
        public bool WithError { get; set; }
        public string ValidationError { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public string TicketNumberOnSupport { get; set; }
        public bool MovedToHistory { get; set; }
        public Nullable<bool> HasInconsistenceError { get; set; }
        public Nullable<bool> HasUnknownRecords { get; set; }
        public string UnknownRecords { get; set; }
        public int TotalUnknownRecords { get; set; }
        public Nullable<System.DateTime> RealFileDate { get; set; }
        public Nullable<int> ProductId { get; set; }
    }
}
