//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int NotificationLogId { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> TicketLogId { get; set; }
        public string TypeFormat { get; set; }
        public string HtmlNotification { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual TicketLog TicketLog { get; set; }
    }
}
