//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpsServiceResponses
    {
        public NpsServiceResponses()
        {
            this.NpsServiceResponseQueryTrxs = new HashSet<NpsServiceResponseQueryTrxs>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SvcReqId { get; set; }
        public Nullable<int> Code { get; set; }
        public string Message { get; set; }
        public string Extended { get; set; }
        public Nullable<long> TrxId { get; set; }
        public Nullable<long> OriginalTrxId { get; set; }
        public string Session { get; set; }
        public string FrontPSPUrl { get; set; }
        public string MerchantId { get; set; }
        public string MerchantMail { get; set; }
        public string MerchTrxRef { get; set; }
        public string MerchOrderId { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> NumPayments { get; set; }
        public Nullable<long> PaymentAmount { get; set; }
        public Nullable<int> Recurrent { get; set; }
        public Nullable<long> RefundedAmount { get; set; }
        public Nullable<long> CapturedAmount { get; set; }
        public Nullable<long> AuthorizedAmount { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<int> BatchNbr { get; set; }
        public Nullable<int> TicketNbr { get; set; }
        public string TicketDescription { get; set; }
        public string ScreenDescription { get; set; }
        public Nullable<int> SequenceNbr { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<System.DateTime> Exp1Date { get; set; }
        public Nullable<long> Exp1Amount { get; set; }
        public Nullable<System.DateTime> Exp2Date { get; set; }
        public Nullable<long> Exp2Amount { get; set; }
        public Nullable<System.DateTime> Exp3Date { get; set; }
        public Nullable<long> Exp3Amount { get; set; }
        public Nullable<long> MinAmount { get; set; }
        public Nullable<int> ExpMark { get; set; }
        public Nullable<System.TimeSpan> ExpTime { get; set; }
        public string CustomerId { get; set; }
        public string CustomerMail { get; set; }
        public string CustomerDocType { get; set; }
        public string CustomerDocNbr { get; set; }
        public string Plan { get; set; }
        public Nullable<System.DateTime> FirstPaymentDeferralDate { get; set; }
        public Nullable<int> ClTrxId { get; set; }
        public Nullable<long> ClExternalMerchant { get; set; }
        public Nullable<long> ClExternalTerminal { get; set; }
        public Nullable<int> ClResponseCode { get; set; }
        public string ClResponseMessage { get; set; }
        public string QueryCriteria { get; set; }
        public string QueryCriteriaId { get; set; }
        public Nullable<System.DateTime> PosDateTime { get; set; }
        public string BarCode { get; set; }
    
        public virtual NpsServiceRequests NpsServiceRequests { get; set; }
        public virtual ICollection<NpsServiceResponseQueryTrxs> NpsServiceResponseQueryTrxs { get; set; }
    }
}
