//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpsServiceRequests
    {
        public NpsServiceRequests()
        {
            this.NpsServiceResponses = new HashSet<NpsServiceResponses>();
        }
    
        public long Id { get; set; }
        public string Type { get; set; }
        public string Version { get; set; }
        public string TrxSource { get; set; }
        public string MerchantId { get; set; }
        public string MerchantMail { get; set; }
        public string MerchTrxRef { get; set; }
        public string MerchOrderId { get; set; }
        public Nullable<long> OriginalTrxId { get; set; }
        public string ReturnUrl { get; set; }
        public string FrmBackButtonUrl { get; set; }
        public string FrmLanguage { get; set; }
        public string TicketDescription { get; set; }
        public string ScreenDescription { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> NumPayments { get; set; }
        public Nullable<long> PaymentAmount { get; set; }
        public Nullable<int> Recurrent { get; set; }
        public string Plan { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<System.DateTime> Exp1Date { get; set; }
        public Nullable<long> Exp1Amount { get; set; }
        public Nullable<int> DaysUntilExp2Date { get; set; }
        public Nullable<System.DateTime> Exp2Date { get; set; }
        public Nullable<long> Exp2Amount { get; set; }
        public Nullable<System.DateTime> Exp3Date { get; set; }
        public Nullable<long> Exp3Amount { get; set; }
        public Nullable<long> MinAmount { get; set; }
        public Nullable<int> ExpMark { get; set; }
        public Nullable<System.TimeSpan> ExpTime { get; set; }
        public Nullable<int> SurchargeAmount { get; set; }
        public Nullable<int> DaysAvailableToPay { get; set; }
        public string CardNumber { get; set; }
        public string CardExpDate { get; set; }
        public Nullable<int> CardSecurityCode { get; set; }
        public string CardHolderName { get; set; }
        public string UserId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerMail { get; set; }
        public string CustomerDocType { get; set; }
        public string CustomerDocNbr { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerProvince { get; set; }
        public string CustomerLocality { get; set; }
        public string PurchaseDescription { get; set; }
        public string SoftDescriptor { get; set; }
        public Nullable<int> ForceProcessingMethod { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<System.DateTime> FirstPaymentDeferralDate { get; set; }
        public string QueryCriteria { get; set; }
        public string QueryCriteriaId { get; set; }
        public Nullable<System.DateTime> PosDateTime { get; set; }
    
        public virtual ICollection<NpsServiceResponses> NpsServiceResponses { get; set; }
    }
}
