//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpsServiceResponseQueryTrxs
    {
        public long Id { get; set; }
        public long SvcResId { get; set; }
        public Nullable<int> Code { get; set; }
        public string Message { get; set; }
        public string Extended { get; set; }
        public Nullable<int> TrxId { get; set; }
        public string MerchantId { get; set; }
        public string MerchantMail { get; set; }
        public string Operation { get; set; }
        public string TrxSource { get; set; }
        public string MerchTrxRef { get; set; }
        public string MerchOrderId { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> NumPayments { get; set; }
        public Nullable<long> PaymentAmount { get; set; }
        public Nullable<System.DateTime> FirstPaymentDeferralDate { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public Nullable<int> Product { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<int> BatchNbr { get; set; }
        public Nullable<int> SequenceNbr { get; set; }
        public Nullable<int> TicketNbr { get; set; }
        public string CardNbrLfd { get; set; }
        public string CardNbrFsd { get; set; }
        public string CardMask { get; set; }
        public string CardHolderName { get; set; }
        public string CustomerId { get; set; }
        public string CustomerMail { get; set; }
        public Nullable<int> ClTrxId { get; set; }
        public Nullable<long> ClExternalMerchant { get; set; }
        public Nullable<long> ClExternalTerminal { get; set; }
        public Nullable<int> ClResponseCode { get; set; }
        public string ClResponseMessage { get; set; }
        public string PurchaseDescription { get; set; }
        public string Plan { get; set; }
        public Nullable<System.DateTime> PosDateTime { get; set; }
    
        public virtual NpsServiceResponses NpsServiceResponses { get; set; }
    }
}
