//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentClaim
    {
        public PaymentClaim()
        {
            this.AnnulmentJobLog = new HashSet<AnnulmentJobLog>();
            this.AnnulmentRequest = new HashSet<AnnulmentRequest>();
            this.AnnulmentResultInfo = new HashSet<AnnulmentResultInfo>();
            this.CommerceItemClaim = new HashSet<CommerceItemClaim>();
            this.PaymentClaimStatus = new HashSet<PaymentClaimStatus>();
        }
    
        public long PaymentClaimId { get; set; }
        public long PaymentClaimNumber { get; set; }
        public Nullable<int> ClaimerId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Observation { get; set; }
        public bool IsAutomatic { get; set; }
        public bool IsLocked { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<AnnulmentJobLog> AnnulmentJobLog { get; set; }
        public virtual ICollection<AnnulmentRequest> AnnulmentRequest { get; set; }
        public virtual ICollection<AnnulmentResultInfo> AnnulmentResultInfo { get; set; }
        public virtual Claimer Claimer { get; set; }
        public virtual ICollection<CommerceItemClaim> CommerceItemClaim { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Transactions Transactions { get; set; }
        public virtual ICollection<PaymentClaimStatus> PaymentClaimStatus { get; set; }
    }
}
