//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentClaimStatus
    {
        public int PaymentClaimStatusId { get; set; }
        public Nullable<long> PaymentClaimId { get; set; }
        public Nullable<int> StatusCodeId { get; set; }
        public string Observation { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public bool IsActual { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual PaymentClaim PaymentClaim { get; set; }
        public virtual StatusCode StatusCode { get; set; }
    }
}
