//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCarpendi
    {
        public int ProductCarpendiId { get; set; }
        public int ProductId { get; set; }
        public string CarpendiProductId { get; set; }
        public bool deleted { get; set; }
    }
}
