//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsValidators
    {
        public int ProductValidatorId { get; set; }
        public int ProductId { get; set; }
        public int ValidatorId { get; set; }
        public int CardCode { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Validators Validators { get; set; }
    }
}
