//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refunds
    {
        public Refunds()
        {
            this.RefundsRecords = new HashSet<RefundsRecords>();
        }
    
        public long Id { get; set; }
        public long ClaimOperationId { get; set; }
        public long OriginalTrxId { get; set; }
        public long AmountToRefund { get; set; }
        public bool ClientValidated { get; set; }
        public bool ClientValidationResult { get; set; }
        public Nullable<System.DateTime> ClientValidationDate { get; set; }
        public string ClientMessage { get; set; }
        public Nullable<System.DateTime> RobotRunDate { get; set; }
        public int ValidatorId { get; set; }
        public bool ValidatorValidated { get; set; }
        public bool ValidatorValidationResult { get; set; }
        public Nullable<System.DateTime> ValidatorValidationDate { get; set; }
        public string ValidatorMessage { get; set; }
        public bool CallCenterValidated { get; set; }
        public bool CallCenterValidationResult { get; set; }
        public Nullable<System.DateTime> CallCenterValidationDate { get; set; }
        public string CallCenterMessage { get; set; }
        public Nullable<System.DateTime> MailSendedToCustomerDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<short> Retries { get; set; }
    
        public virtual ClaimOperations ClaimOperations { get; set; }
        public virtual ICollection<RefundsRecords> RefundsRecords { get; set; }
    }
}
