//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.UserRol = new HashSet<UserRol>();
        }
    
        public int Id { get; set; }
        public string shortName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UserRol> UserRol { get; set; }
    }
}
