//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.Configurations = new HashSet<Configurations>();
            this.NotificationConfig = new HashSet<NotificationConfig>();
            this.ServicesConfig = new HashSet<ServicesConfig>();
            this.TransactionAdditionalInfo = new HashSet<TransactionAdditionalInfo>();
            this.UserService = new HashSet<UserService>();
            this.ValidatorServiceConfig = new HashSet<ValidatorServiceConfig>();
        }
    
        public int ServiceId { get; set; }
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MerchantId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Configurations> Configurations { get; set; }
        public virtual ICollection<NotificationConfig> NotificationConfig { get; set; }
        public virtual ICollection<ServicesConfig> ServicesConfig { get; set; }
        public virtual ICollection<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
        public virtual ICollection<UserService> UserService { get; set; }
        public virtual ICollection<ValidatorServiceConfig> ValidatorServiceConfig { get; set; }
    }
}
