//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpsBatchTemporalValidation
    {
        public long TransactionNumber { get; set; }
        public int MedioDePago { get; set; }
        public System.DateTime FechaDeOperacion { get; set; }
        public long CurrentAmount { get; set; }
        public long IDSITE { get; set; }
        public bool EsCargo { get; set; }
    }
}
