//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpsBatch
    {
        public int Id { get; set; }
        public string BatchCommerceNbr { get; set; }
        public string BatchDate { get; set; }
        public string BatchCard { get; set; }
        public string TransactionId { get; set; }
        public string CardCode { get; set; }
        public string CardNumber { get; set; }
        public string OperationType { get; set; }
        public string OperationDate { get; set; }
        public string OperationAmount { get; set; }
        public string AuthorizationCode { get; set; }
        public string CouponNumber { get; set; }
        public string CommerceNumber { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int Payments { get; set; }
        public string CloseDate { get; set; }
        public string EstablishmentNumber { get; set; }
    }
}
