//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpsServiceResponses
    {
        public long Id { get; set; }
        public Nullable<long> SvcReqId { get; set; }
        public string Reason { get; set; }
        public string Currency { get; set; }
        public string DeliveryAddress { get; set; }
        public string AddressValidation { get; set; }
        public string OrderCode { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PurchaserTelephone { get; set; }
        public string DeliveryDistrict { get; set; }
        public string AuthorizationCode { get; set; }
        public string DeliveryCountry { get; set; }
        public Nullable<int> Quotes { get; set; }
        public string IsDateOfBirthValidated { get; set; }
        public string IsDocNumValidated { get; set; }
        public string Holder { get; set; }
        public string Order { get; set; }
        public string ZipNumDelivery { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Card { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PurchaserMail { get; set; }
        public string IsGateNumValidated { get; set; }
        public string DeliveryCity { get; set; }
        public string IsDocTypeValidated { get; set; }
        public string OperationNumber { get; set; }
        public string DeliveryState { get; set; }
        public string Result { get; set; }
        public string DeliveryMessage { get; set; }
        public string SiteParameter { get; set; }
        public string DocType { get; set; }
        public string DocTypeDescription { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public Nullable<System.DateTime> ChargebackDate { get; set; }
        public string chargebackReason { get; set; }
        public string chargebackSite { get; set; }
        public string AuthenticationResultVbv { get; set; }
        public string VisibleCardNum { get; set; }
        public string AditionalReason { get; set; }
        public string TicketNum { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string idMotivo { get; set; }
    
        public virtual SpsServiceRequests SpsServiceRequests { get; set; }
    }
}
