//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpsServiceRequests
    {
        public SpsServiceRequests()
        {
            this.SpsServiceResponses = new HashSet<SpsServiceResponses>();
        }
    
        public long Id { get; set; }
        public string CommerceNumber { get; set; }
        public string OperationNumber { get; set; }
        public string Amount { get; set; }
        public string Payments { get; set; }
        public string CallbackUrl { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string MailAddress { get; set; }
        public string ParamSitio { get; set; }
        public string ReturnUrl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<SpsServiceResponses> SpsServiceResponses { get; set; }
    }
}
