//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionStatus
    {
        public int TransactionStatusId { get; set; }
        public long TransactionsId { get; set; }
        public int StatusCodeId { get; set; }
        public bool IsActual { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Transactions Transactions { get; set; }
        public virtual StatusCode StatusCode { get; set; }
    }
}
