//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRol = new HashSet<UserRol>();
            this.UserService = new HashSet<UserService>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public int pswdId { get; set; }
        public string email { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Pswd Pswd { get; set; }
        public virtual ICollection<UserRol> UserRol { get; set; }
        public virtual ICollection<UserService> UserService { get; set; }
    }
}
