//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public long Id { get; set; }
        public int ut { get; set; }
        public Nullable<long> r { get; set; }
        public byte[] a { get; set; }
    }
}
