//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validators
    {
        public Validators()
        {
            this.Configurations = new HashSet<Configurations>();
            this.ProductsValidators = new HashSet<ProductsValidators>();
            this.TransactionAdditionalInfo = new HashSet<TransactionAdditionalInfo>();
            this.ValidatorServiceConfig = new HashSet<ValidatorServiceConfig>();
        }
    
        public int ValidatorId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool GenerateTransactionId { get; set; }
        public bool SendMail { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Configurations> Configurations { get; set; }
        public virtual ICollection<ProductsValidators> ProductsValidators { get; set; }
        public virtual ICollection<TransactionAdditionalInfo> TransactionAdditionalInfo { get; set; }
        public virtual ICollection<ValidatorServiceConfig> ValidatorServiceConfig { get; set; }
    }
}
