//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetPaymentTicketInfo
    {
        public int TRIId { get; set; }
        public System.DateTime TAICreatedOn { get; set; }
        public string responseCode { get; set; }
        public string moduleDescription { get; set; }
        public int serviceId { get; set; }
        public string customerMail { get; set; }
        public decimal amount { get; set; }
        public string authcode { get; set; }
        public string cardmask { get; set; }
        public string currencyIsoCode { get; set; }
        public string productName { get; set; }
        public string serviceDescription { get; set; }
        public long transactionId { get; set; }
    }
}
