//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSvcMethodParams
    {
        public WebSvcMethodParams()
        {
            this.ConfigurationDefaultValues = new HashSet<ConfigurationDefaultValues>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProposedValue { get; set; }
        public bool IsActive { get; set; }
        public int WebSvcMethodId { get; set; }
    
        public virtual ICollection<ConfigurationDefaultValues> ConfigurationDefaultValues { get; set; }
        public virtual WebSvcMethods WebSvcMethods { get; set; }
    }
}
