//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSvcMethods
    {
        public WebSvcMethods()
        {
            this.ConfigurationDefaultValues = new HashSet<ConfigurationDefaultValues>();
            this.ConfigurationDetails = new HashSet<ConfigurationDetails>();
            this.ConfigurationDetails1 = new HashSet<ConfigurationDetails>();
            this.WebSvcMethodParams = new HashSet<WebSvcMethodParams>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal TrxCost { get; set; }
        public bool IsActive { get; set; }
        public int ValidatorId { get; set; }
        public bool IsRefund { get; set; }
    
        public virtual ICollection<ConfigurationDefaultValues> ConfigurationDefaultValues { get; set; }
        public virtual ICollection<ConfigurationDetails> ConfigurationDetails { get; set; }
        public virtual ICollection<ConfigurationDetails> ConfigurationDetails1 { get; set; }
        public virtual ICollection<WebSvcMethodParams> WebSvcMethodParams { get; set; }
    }
}
