//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSyncro.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeMapping
    {
        public int CodeMappingId { get; set; }
        public int ModuleCodeId { get; set; }
        public int StatusCodeId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ModuleCode ModuleCode { get; set; }
        public virtual StatusCode StatusCode { get; set; }
    }
}
