//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSyncro.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorSyncroProcess
    {
        public long MonitorSyncroProcessId { get; set; }
        public System.DateTime BeginOn { get; set; }
        public Nullable<System.DateTime> EndOn { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool WithProcessError { get; set; }
        public long TotalTransactionsToSync { get; set; }
        public long TotalTransactionsProcessed { get; set; }
        public long TotalTransactionsClosed { get; set; }
        public long TotalTransactionsWithError { get; set; }
        public long TotalTransactionsNotClosed { get; set; }
        public long TotalTransactionsClosedOK { get; set; }
        public long TotalTransactionsClosedNO { get; set; }
        public long TotalTransactionsClosedERROR { get; set; }
        public long TotalTransactionsClosedNA { get; set; }
        public long TotalTransactionsClosedNAByTIMEOUT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
