//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSyncro.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PaymentGatewayEntities : DbContext
    {
        public PaymentGatewayEntities()
            : base("name=PaymentGatewayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonitorSyncroProcess> MonitorSyncroProcesses { get; set; }
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
        public virtual DbSet<ValidatorServiceConfig> ValidatorServiceConfigs { get; set; }
        public virtual DbSet<TransactionResultInfo> TransactionResultInfoes { get; set; }
        public virtual DbSet<TransactionStatu> TransactionStatus { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleCode> ModuleCodes { get; set; }
        public virtual DbSet<CodeMapping> CodeMappings { get; set; }
        public virtual DbSet<GenericCode> GenericCodes { get; set; }
        public virtual DbSet<StatusCode> StatusCodes { get; set; }
        public virtual DbSet<MonitorSyncroProcessRecord> MonitorSyncroProcessRecords { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    
        public virtual ObjectResult<GetTransactionsToSync_Result> GetTransactionsToSync()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTransactionsToSync_Result>("GetTransactionsToSync");
        }
    }
}
