//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSyncro.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidatorServiceConfig
    {
        public int ValidatorServiceConfigId { get; set; }
        public int ValidatorId { get; set; }
        public int ServiceId { get; set; }
        public string ValidatorUser { get; set; }
        public string ValidatorPass { get; set; }
        public string HashKey { get; set; }
    }
}
