//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PGPluginSPS.SpsServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OperationSoap11Binding", Namespace="urn:Decidir.net")]
    public partial class Operation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Operation() {
            this.Url = global::PGPluginSPS.Properties.Settings.Default.PGPluginSPS_SpsServiceReference_Operation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCompletedEventHandler GetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Get", RequestNamespace="urn:Decidir.net", ResponseElementName="Operations", ResponseNamespace="urn:Decidir.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Error", typeof(Error))]
        [return: System.Xml.Serialization.XmlElementAttribute("Operation", typeof(Operation1))]
        public object[] Get([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IDSITE, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IDTRANSACTIONSIT) {
            object[] results = this.Invoke("Get", new object[] {
                        IDSITE,
                        IDTRANSACTIONSIT});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAsync(string IDSITE, string IDTRANSACTIONSIT) {
            this.GetAsync(IDSITE, IDTRANSACTIONSIT, null);
        }
        
        /// <remarks/>
        public void GetAsync(string IDSITE, string IDTRANSACTIONSIT, object userState) {
            if ((this.GetOperationCompleted == null)) {
                this.GetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperationCompleted);
            }
            this.InvokeAsync("Get", new object[] {
                        IDSITE,
                        IDTRANSACTIONSIT}, this.GetOperationCompleted, userState);
        }
        
        private void OnGetOperationCompleted(object arg) {
            if ((this.GetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompleted(this, new GetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Decidir.net")]
    public partial class Error {
        
        private string eRRCODEField;
        
        private string eRRDESCField;
        
        /// <remarks/>
        public string ERRCODE {
            get {
                return this.eRRCODEField;
            }
            set {
                this.eRRCODEField = value;
            }
        }
        
        /// <remarks/>
        public string ERRDESC {
            get {
                return this.eRRDESCField;
            }
            set {
                this.eRRDESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Decidir.net")]
    public partial class SUBTRANSACTION {
        
        private string iDTRANSACCIONSITEField;
        
        private string mONTOField;
        
        private string cUOTASField;
        
        private string nROTICKETField;
        
        private string eSTADO_DESCRIField;
        
        private string iDMOTIVOField;
        
        private string mOTIVO_ADICIONALField;
        
        private string cODAUTField;
        
        private string mOTIVOField;
        
        private string iDSITEField;
        
        private string iDESTADOField;
        
        private string tERMINALField;
        
        private string lOTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDTRANSACCIONSITE {
            get {
                return this.iDTRANSACCIONSITEField;
            }
            set {
                this.iDTRANSACCIONSITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CUOTAS {
            get {
                return this.cUOTASField;
            }
            set {
                this.cUOTASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NROTICKET {
            get {
                return this.nROTICKETField;
            }
            set {
                this.nROTICKETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO_DESCRI {
            get {
                return this.eSTADO_DESCRIField;
            }
            set {
                this.eSTADO_DESCRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDMOTIVO {
            get {
                return this.iDMOTIVOField;
            }
            set {
                this.iDMOTIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOTIVO_ADICIONAL {
            get {
                return this.mOTIVO_ADICIONALField;
            }
            set {
                this.mOTIVO_ADICIONALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODAUT {
            get {
                return this.cODAUTField;
            }
            set {
                this.cODAUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOTIVO {
            get {
                return this.mOTIVOField;
            }
            set {
                this.mOTIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDSITE {
            get {
                return this.iDSITEField;
            }
            set {
                this.iDSITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDESTADO {
            get {
                return this.iDESTADOField;
            }
            set {
                this.iDESTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TERMINAL {
            get {
                return this.tERMINALField;
            }
            set {
                this.tERMINALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOTE {
            get {
                return this.lOTEField;
            }
            set {
                this.lOTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Operation", Namespace="urn:Decidir.net")]
    public partial class Operation1 {
        
        private string iDTRANSACCIONSITEField;
        
        private string fECHA_ORIGINALField;
        
        private string mONTOField;
        
        private string cUOTASField;
        
        private string nROTICKETField;
        
        private string eSTADO_DESCRIField;
        
        private string iDMOTIVOField;
        
        private string mOTIVO_ADICIONALField;
        
        private string tITULARField;
        
        private string iDTIPODOCField;
        
        private string nRODOCField;
        
        private string tIPODOCField;
        
        private string cODAUTField;
        
        private string nROTARJ4Field;
        
        private string mOTIVOField;
        
        private string vALDOMField;
        
        private string mAILField;
        
        private string iDSITEField;
        
        private string iDESTADOField;
        
        private string iDMEDIOPAGOField;
        
        private string mEDIOPAGO_DESCRIField;
        
        private string sEXOTITULARField;
        
        private string cALLEField;
        
        private string nROPUERTAField;
        
        private string pARAMSITIOField;
        
        private string fECHAVTOCUOTA1Field;
        
        private string iDOPERACIONMEDIOPAGOField;
        
        private string tERMINALField;
        
        private string lOTEField;
        
        private string rESULTADOCSField;
        
        private string iDENTIFICADORCSField;
        
        private SUBTRANSACTION[] sUBTRANSACTIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDTRANSACCIONSITE {
            get {
                return this.iDTRANSACCIONSITEField;
            }
            set {
                this.iDTRANSACCIONSITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHA_ORIGINAL {
            get {
                return this.fECHA_ORIGINALField;
            }
            set {
                this.fECHA_ORIGINALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CUOTAS {
            get {
                return this.cUOTASField;
            }
            set {
                this.cUOTASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NROTICKET {
            get {
                return this.nROTICKETField;
            }
            set {
                this.nROTICKETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO_DESCRI {
            get {
                return this.eSTADO_DESCRIField;
            }
            set {
                this.eSTADO_DESCRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDMOTIVO {
            get {
                return this.iDMOTIVOField;
            }
            set {
                this.iDMOTIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOTIVO_ADICIONAL {
            get {
                return this.mOTIVO_ADICIONALField;
            }
            set {
                this.mOTIVO_ADICIONALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TITULAR {
            get {
                return this.tITULARField;
            }
            set {
                this.tITULARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDTIPODOC {
            get {
                return this.iDTIPODOCField;
            }
            set {
                this.iDTIPODOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NRODOC {
            get {
                return this.nRODOCField;
            }
            set {
                this.nRODOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TIPODOC {
            get {
                return this.tIPODOCField;
            }
            set {
                this.tIPODOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODAUT {
            get {
                return this.cODAUTField;
            }
            set {
                this.cODAUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NROTARJ4 {
            get {
                return this.nROTARJ4Field;
            }
            set {
                this.nROTARJ4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOTIVO {
            get {
                return this.mOTIVOField;
            }
            set {
                this.mOTIVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VALDOM {
            get {
                return this.vALDOMField;
            }
            set {
                this.vALDOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MAIL {
            get {
                return this.mAILField;
            }
            set {
                this.mAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDSITE {
            get {
                return this.iDSITEField;
            }
            set {
                this.iDSITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDESTADO {
            get {
                return this.iDESTADOField;
            }
            set {
                this.iDESTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDMEDIOPAGO {
            get {
                return this.iDMEDIOPAGOField;
            }
            set {
                this.iDMEDIOPAGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MEDIOPAGO_DESCRI {
            get {
                return this.mEDIOPAGO_DESCRIField;
            }
            set {
                this.mEDIOPAGO_DESCRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SEXOTITULAR {
            get {
                return this.sEXOTITULARField;
            }
            set {
                this.sEXOTITULARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CALLE {
            get {
                return this.cALLEField;
            }
            set {
                this.cALLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NROPUERTA {
            get {
                return this.nROPUERTAField;
            }
            set {
                this.nROPUERTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PARAMSITIO {
            get {
                return this.pARAMSITIOField;
            }
            set {
                this.pARAMSITIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAVTOCUOTA1 {
            get {
                return this.fECHAVTOCUOTA1Field;
            }
            set {
                this.fECHAVTOCUOTA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDOPERACIONMEDIOPAGO {
            get {
                return this.iDOPERACIONMEDIOPAGOField;
            }
            set {
                this.iDOPERACIONMEDIOPAGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TERMINAL {
            get {
                return this.tERMINALField;
            }
            set {
                this.tERMINALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LOTE {
            get {
                return this.lOTEField;
            }
            set {
                this.lOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESULTADOCS {
            get {
                return this.rESULTADOCSField;
            }
            set {
                this.rESULTADOCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDENTIFICADORCS {
            get {
                return this.iDENTIFICADORCSField;
            }
            set {
                this.iDENTIFICADORCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SUBTRANSACTION[] SUBTRANSACTIONS {
            get {
                return this.sUBTRANSACTIONSField;
            }
            set {
                this.sUBTRANSACTIONSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCompletedEventHandler(object sender, GetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591